import {courses,activateCatalog} from './curriculum.js?v=7';
import {mountCurriculumImport} from './curriculum-ui.js?v=7';
import {electiveDone,electiveTarget,areas,colors,fresh,totals,eligible,completedIDs,requirements,combinations,validateState} from './logic.js?v=7';
import {parseCalendar,monday,weekEvents} from './calendar.js';
import {load,save} from './storage.js';
import {exportPNG} from './export.js?v=7';
const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#detail');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat('de-AT',{maximumFractionDigits:1}).format(n);
const date=d=>new Intl.DateTimeFormat('de-AT',{day:'numeric',month:'short'}).format(d);
const time=d=>new Intl.DateTimeFormat('de-AT',{hour:'2-digit',minute:'2-digit'}).format(d);
let state=fresh(),calendar=[],week=monday(new Date()),search='',status='',prereq='',type='',target=4,visibleEvents=[],storageReady=true;
function notify(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').hidden=true,6500);}
async function commit(next){if(!storageReady)throw Error('Speicher nicht verfügbar. Bitte Daten sichern und Browser-Speicher prüfen.');await save(next);state=next;activateCatalog(state);render();}
const clone=()=>structuredClone(state);
const metric=(title,value,detail)=>`<div class="card metric"><small>${title}</small><strong>${value}</strong><small>${detail}</small></div>`;
function progressFor(c){return c.type==='elective'?{status:electiveDone(c,state)>=c.ects?'completed':'planned'}:state.progress[c.id]||{status:'planned'};}
const labels={planned:'Offen',inProgress:'Laufend',completed:'Erledigt'};
function courseRow(c){const p=progressFor(c);return `<button class="course" data-course="${c.id}"><span><strong>${esc(c.title)}</strong><small>${esc(c.module)} · ${number(c.ects)} ECTS${p.grade?' · Note '+esc(p.grade):''}</small></span><span class="badge ${p.status==='completed'?'done':''}">${labels[p.status]}</span></button>`;}
function home(){const t=totals(state);return `<section class="hero"><span class="eyebrow">Dein persönlicher Studienbegleiter</span><h1>Ein Schritt näher<br>an deinem Abschluss.</h1><p class="muted">Vorlesungen, Fortschritt und die nächste Woche. Alles an einem Ort.</p><div class="row"><strong>${number(t.done)} von ${t.total} ECTS</strong><span class="muted">${number(t.total-t.done)} ECTS offen</span></div><p><progress value="${t.done}" max="${t.total}" aria-label="Studienfortschritt"></progress></p><div class="actions"><a class="button primary" href="#schedule">Meine Woche ansehen</a><a class="button" href="#courses">Studienplan öffnen</a></div></section><div class="grid">${metric('Fortschritt',number(t.done/Math.max(1,t.total)*100)+' %','deines Studienplans')}${metric('Notenschnitt',t.average?number(t.average):'–','nach ECTS gewichtet')}${metric('Wahlfach',number(Math.min(t.ww,electiveTarget()))+' / '+electiveTarget(),'abgeschlossene WW-ECTS')}${metric('Stundenplan',state.calendar?'Importiert':'Noch offen',esc(state.calendar?.name||'ICS-Datei hinzufügen'))}</div><section class="card"><h2>Deine Modulgruppen</h2><div class="grid">${Object.entries(areas).map(([key,label])=>{const cs=courses.filter(c=>c.area===key),total=cs.reduce((n,c)=>n+c.ects,0),done=key==='elective'?Math.min(t.ww,electiveTarget()):cs.filter(c=>progressFor(c).status==='completed').reduce((n,c)=>n+c.ects,0);return `<div class="row"><div><h3>${label}</h3><small>${number(done)} / ${total} ECTS</small></div><div class="ring" style="--percent:${done/Math.max(1,total)*100}%"><span>${Math.round(done/Math.max(1,total)*100)}%</span></div></div>`;}).join('')}</div></section>`;}
function study(){return `<span class="eyebrow">Curriculum 2016</span><h1>Dein Studienplan</h1><div class="actions card"><input id="search" type="search" placeholder="Vorlesung oder Modul suchen" aria-label="Vorlesung suchen" value="${esc(search)}"><select id="status" aria-label="Status"><option value="">Alle Status</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${status===k?'selected':''}>${v}</option>`).join('')}</select><select id="type" aria-label="Lehrform"><option value="">Alle Lehrformen</option>${['vo','vu','ue','uk','lp','elective'].map(k=>`<option ${type===k?'selected':''} value="${k}">${k.toUpperCase()}</option>`).join('')}</select><select id="prereq" aria-label="Voraussetzungen">${[['','Alle Voraussetzungen'],['none','Keine Voraussetzung'],['steop','Nur StEOP'],['eligible','Jetzt belegbar']].map(([k,v])=>`<option value="${k}" ${prereq===k?'selected':''}>${v}</option>`).join('')}</select></div><div id="course-list">${courseList()}</div>`;}
function courseList(){const filtered=courses.filter(c=>(c.title+' '+c.moduleTitle+' '+c.module).toLowerCase().includes(search.toLowerCase())&&(!status||progressFor(c).status===status)&&(!type||c.type===type)&&(!prereq||(prereq==='none'&&!c.requires.length)||(prereq==='steop'&&c.requires.length===1&&c.requires[0]==='StEOP')||(prereq==='eligible'&&progressFor(c).status!=='completed'&&eligible(c,completedIDs(state)))));return [...new Set(courses.map(c=>c.term.order))].map(order=>{const cs=filtered.filter(c=>c.term.order===order);return cs.length?`<details class="card" ${search||status||prereq||type?'open':''}><summary>${esc(cs[0].term.title)} <small>${cs.length} LV</small></summary>${cs.map(courseRow).join('')}</details>`:'';}).join('')||'<p class="empty">Keine passenden Lehrveranstaltungen gefunden.</p>';}
function match(event){if(state.links[event.key])return courses.find(c=>c.id===state.links[event.key]);const normalized=s=>s.toLowerCase().replace(/^(vo|vu|ue|uk|lp)\s+/,'').replace(/[^\p{L}\p{N}]/gu,'');const title=normalized(event.title);const matches=courses.filter(c=>c.type!=='elective'&&title.includes(normalized(c.title)));return matches.length===1?matches[0]:null;}
function tint(event){const c=match(event);if(state.eventColors[event.key])return state.eventColors[event.key];if(c&&state.progress[c.id]?.color)return state.progress[c.id].color;if(state.rule==='exam')return /prüfung|pruefung|klausur|exam|testat/i.test(event.title)?'#b3445a':'#246bc1';if(state.rule==='term')return c?colors[(c.term.order-1)%colors.length]:'#607589';return c?colors[Object.keys(areas).indexOf(c.area)%colors.length]:'#607589';}
function schedule(){let error='';try{visibleEvents=weekEvents(calendar,week);}catch(e){visibleEvents=[];error=e.message;}const end=new Date(week);end.setDate(end.getDate()+6);const weekends=visibleEvents.some(e=>[0,6].includes(e.start.getDay()));return `<span class="eyebrow">Deine Termine</span><h1>Eine Woche im Blick.</h1><section class="card"><div class="row"><div><h2>${date(week)} – ${date(end)} ${week.getFullYear()}</h2><small>${esc(state.calendar?.name||'Noch kein Stundenplan importiert')}</small></div><button class="primary" data-action="import">ICS ${state.calendar?'ersetzen':'importieren'}</button></div><p></p><div class="actions"><button data-action="prev" aria-label="Vorherige Woche">←</button><button data-action="today">Diese Woche</button><button data-action="next" aria-label="Nächste Woche">→</button><label>Woche wählen <input type="date" id="week-date" value="${localDate(week)}"></label><label>Farben <select id="rule">${[['studyArea','Modulgruppe'],['term','Semester'],['exam','Prüfungen']].map(([k,v])=>`<option value="${k}" ${state.rule===k?'selected':''}>${v}</option>`).join('')}</select></label></div>${error?`<p class="warning">${esc(error)}</p>`:''}${!state.calendar?'<p class="empty">Importiere deinen Uni-Kalender. Der Import bleibt nach dem Schließen dieses Browsers gespeichert.</p>':''}<div class="week">${Array.from({length:weekends?7:5},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);const ev=visibleEvents.filter(e=>e.start<new Date(d.getFullYear(),d.getMonth(),d.getDate()+1)&&e.end>d);return `<section class="day"><h3>${['Mo','Di','Mi','Do','Fr','Sa','So'][i]} · ${date(d)}</h3>${ev.map(e=>`<button class="event" data-event="${visibleEvents.indexOf(e)}" style="--event:${tint(e)}"><time>${e.allDay?'Ganztägig':time(e.start)+' – '+time(e.end)}</time><strong>${esc(e.title)}</strong>${e.location?`<small>${esc(e.location)}</small>`:''}</button>`).join('')||'<p class="empty">Keine Termine</p>'}</section>`;}).join('')}</div></section>`;}
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function stats(){const t=totals(state),p=combinations(state,target);return `<span class="eyebrow">Fortschritt & Planung</span><h1>Jeder ECTS zählt.</h1><div class="grid">${metric('Abgeschlossen',number(t.done)+' ECTS','von '+t.total)}${metric('Notenschnitt',t.average?number(t.average):'–','abgeschlossene, benotete LV')}</div><section class="card"><h2>ECTS-Rechner</h2><label>Abschluss in weiteren Semestern <input id="target" type="number" min="1" max="20" value="${target}"></label><p><strong>${number(p.target)} ECTS pro Semester</strong> bei ${number(t.total-t.done)} verbleibenden ECTS.</p><p class="muted">Kombinationen für dein nächstes Semester: nur offene LV mit bereits erfüllten Pflichtvoraussetzungen. Spätere Semester müssen nach deinem Fortschritt neu geplant werden.</p><p class="warning">Das tatsächliche Semesterangebot, Anmeldungen und Überschneidungen sind nicht geprüft. Empfohlene Semester sind keine Zusage für Winter- oder Sommerangebote. WW muss separat mit passenden Wahlfächern geplant werden.</p>${p.choices.map((choice,i)=>`<details ${i===0?'open':''}><summary>Vorschlag ${i+1} · ${number(choice.ects)} ECTS</summary>${choice.items.map(courseRow).join('')}<small>Abweichung vom Ziel: ${number(choice.ects-p.target)} ECTS</small></details>`).join('')||'<p>Keine offenen, bereits freigeschalteten Pflicht-LV verfügbar.</p>'}</section><section class="card bars"><h2>ECTS nach empfohlenem Semester</h2><p class="muted">Wahlfach-ECTS werden für diese Übersicht der Reihe nach auf die Wahlfachblöcke verteilt; dies ersetzt keine Anerkennung.</p>${[...new Set(courses.map(c=>c.term.order))].map(order=>{const cs=courses.filter(c=>c.term.order===order),sum=cs.reduce((n,c)=>n+c.ects,0),done=cs.reduce((n,c)=>n+(c.type==='elective'?electiveDone(c,state):progressFor(c).status==='completed'?c.ects:0),0);return `<div><div class="row"><span>${esc(cs[0].term.title)}</span><strong>${number(done)} / ${sum}</strong></div><progress max="${sum}" value="${done}"></progress></div>`;}).join('')}</section><section class="card"><h2>Offene Pflicht-LV</h2>${courses.filter(c=>c.type!=='elective'&&progressFor(c).status!=='completed').map(courseRow).join('')||'<p>Alle Pflicht-LV abgeschlossen.</p>'}</section><button data-action="print">Übersicht drucken / als PDF sichern</button>`;}
function dataView(){return `<span class="eyebrow">Deine Daten</span><h1>Alles bleibt bei dir.</h1><section class="card"><h2>Backup & Übernahme</h2><p>Noten, Status, Notizen, Farben und ICS-Datei liegen ausschließlich in diesem Browser. Das Hosting erhält diese Einträge nicht. Ein Browserwechsel oder gelöschte Website-Daten können sie entfernen.</p><div class="actions"><button data-action="backup" class="primary">Backup herunterladen</button><button data-action="restore">Backup wiederherstellen</button><button data-action="persist">Dauerhaften Speicher anfragen</button></div><p class="muted">Das Backup enthält persönliche Daten. Bewahre es privat auf. Die iOS-Daten werden nicht automatisch übertragen; deine ICS-Datei kannst du hier erneut importieren.</p></section><section class="card"><h2>Auf dem iPhone</h2><p>Öffne die veröffentlichte Adresse in Safari. Über Teilen → Zum Home-Bildschirm kannst du CatchStudy wie eine App starten. Nach dem ersten Laden ist die Oberfläche auch offline verfügbar.</p></section><section class="card"><h2>Kalender entfernen</h2><p>Studienfortschritt und Noten bleiben dabei erhalten.</p><button data-action="clear-calendar" class="danger">Importierten Stundenplan löschen</button></section>`;}
function statisticsExtras(){return `<section class="card bars"><h2>Notenschnitt nach empfohlenem Semester</h2><p class="muted">ECTS-gewichtet, nur abgeschlossene LV mit Note. Dies ist keine zeitliche Prüfungsverlaufskurve.</p>${[...new Set(courses.map(c=>c.term.order))].map(order=>{const cs=courses.filter(c=>c.term.order===order),graded=cs.filter(c=>c.type!=='elective'&&progressFor(c).status==='completed'&&+progressFor(c).grade>=1).map(c=>({ects:c.ects,grade:+progressFor(c).grade}));if(cs.some(c=>c.type==='elective'))graded.push(...state.electives.filter(e=>e.completed&&+e.grade>=1));const weight=graded.reduce((n,c)=>n+c.ects,0),average=weight?graded.reduce((n,c)=>n+c.ects*+c.grade,0)/weight:null;return `<div class="row"><span>${cs[0].term.title}</span><strong>${average?number(average):'Noch keine Noten'}</strong></div>`;}).join('')}</section><section class="card bars"><h2>Fortschritt nach Modulgruppen</h2>${Object.entries(areas).map(([key,label])=>{const cs=courses.filter(c=>c.area===key),total=cs.reduce((n,c)=>n+c.ects,0),done=key==='elective'?Math.min(totals(state).ww,electiveTarget()):cs.filter(c=>progressFor(c).status==='completed').reduce((n,c)=>n+c.ects,0);return `<div><div class="row"><span>${label}</span><strong>${number(done)} / ${total} ECTS</strong></div><progress value="${done}" max="${total}"></progress></div>`;}).join('')}</section><button id="png-export">Studienübersicht als PNG</button>`;}
function render(){const route=location.hash.slice(1)||'home';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+route));app.innerHTML=({home, courses:study,schedule,stats,data:dataView}[route]||home)();if(route==='data')mountCurriculumImport(app,()=>state,async next=>commit(validateState(next)));if(state.curriculum){document.querySelector('footer').firstChild.textContent='Eigener Studienplan · '+state.curriculum.name;const eyebrow=app.querySelector('.eyebrow');if(route==='courses')eyebrow.textContent=state.curriculum.name;}if(route==='stats'){app.insertAdjacentHTML('beforeend',statisticsExtras());$('#png-export').addEventListener('click',()=>exportPNG(state));}}
function courseDialog(id){const c=courses.find(c=>c.id===id);if(!c)return;if(c.type==='elective'){electiveDialog();return;}const p=progressFor(c);dialog.innerHTML=`<button class="close" data-action="close" aria-label="Schließen">×</button><h2>${esc(c.title)}</h2><p class="muted">${esc(c.moduleTitle)} · ${c.ects} ECTS</p><p><strong>Voraussetzungen:</strong> ${esc(c.requires.map(r=>requirements(r).map(c=>c.title).join(', ')||r).join('; ')||'Keine')}</p>${c.recommends.length?`<p class="muted">Empfohlen: ${esc(c.recommends.join(', '))}</p>`:''}<form id="course-form" data-id="${c.id}"><label>Status<select name="status">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${p.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Note (1 bis 5)<input name="grade" type="number" min="1" max="5" step="0.1" value="${esc(p.grade||'')}"></label><label>Notizen<textarea name="notes">${esc(p.notes||'')}</textarea></label><label>Eigene Kalenderfarbe<input type="color" name="color" value="${p.color||colors[Object.keys(areas).indexOf(c.area)%colors.length]}"></label><label><input type="checkbox" name="automatic" ${!p.color?'checked':''}> Automatische Farbregel verwenden</label><button class="primary">Speichern</button></form>`;dialog.showModal();}
function electiveDialog(){dialog.innerHTML=`<button class="close" data-action="close" aria-label="Schließen">×</button><h2>Deine Wahlfächer</h2><p>${number(totals(state).ww)} ECTS erledigt · Ziel ${electiveTarget()} ECTS</p>${state.electives.map(e=>`<div class="course"><span><strong>${esc(e.title)}</strong><small>${number(e.ects)} ECTS · ${e.completed?'Erledigt':'Offen'}${e.grade?' · Note '+esc(e.grade):''}</small></span><div class="actions"><button data-edit-elective="${esc(e.id)}">Bearbeiten</button><button data-delete-elective="${esc(e.id)}" aria-label="Wahlfach löschen">×</button></div></div>`).join('')}<h3 style="margin-top:20px">Wahlfach hinzufügen</h3>${electiveForm()}</section>`;if(!dialog.open)dialog.showModal();}
function electiveForm(e={}){return `<form id="elective-form" data-id="${esc(e.id||'')}"><label>Titel<input name="title" required value="${esc(e.title||'')}"></label><label>ECTS<input name="ects" type="number" min="0.1" max="180" step="0.1" value="${e.ects||3}" required></label><label>Note<input name="grade" type="number" min="1" max="5" step="0.1" value="${esc(e.grade||'')}"></label><label><input name="completed" type="checkbox" ${e.completed!==false?'checked':''}> Abgeschlossen</label><button class="primary">Speichern</button></form>`;}
function eventDialog(index){const e=visibleEvents[index],c=match(e);dialog.innerHTML=`<button class="close" data-action="close" aria-label="Schließen">×</button><h2>${esc(e.title)}</h2><p><strong>${date(e.start)} ${time(e.start)} – ${date(e.end)} ${time(e.end)}</strong></p><p>${esc(e.location)}</p><p style="white-space:pre-wrap">${esc(e.notes)}</p><form id="event-form" data-index="${index}"><label>Lehrveranstaltung zuordnen<select name="course"><option value="">Nicht zugeordnet</option>${courses.filter(c=>c.type!=='elective').map(x=>`<option value="${x.id}" ${c?.id===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><label>Eigene Terminfarbe<input name="color" type="color" value="${tint(e)}"></label><label><input name="automatic" type="checkbox" ${!state.eventColors[e.key]?'checked':''}> Automatische Farbregel verwenden</label><div class="actions"><button class="primary">Speichern</button>${c?`<button type="button" data-course="${c.id}">Zur Lehrveranstaltung</button>`:''}</div></form>`;dialog.showModal();}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.dataset.course){dialog.close();courseDialog(button.dataset.course);return;}if(button.dataset.event){eventDialog(+button.dataset.event);return;}if(button.dataset.editElective){const e=state.electives.find(e=>e.id===button.dataset.editElective);dialog.innerHTML=`<button class="close" data-action="close">×</button><h2>Wahlfach bearbeiten</h2>${electiveForm(e)}`;return;}if(button.dataset.deleteElective){if(!confirm('Dieses Wahlfach löschen?'))return;const next=clone();next.electives=next.electives.filter(e=>e.id!==button.dataset.deleteElective);await commit(next);electiveDialog();return;}switch(button.dataset.action){case 'close':dialog.close();break;case 'prev':week.setDate(week.getDate()-7);render();break;case 'next':week.setDate(week.getDate()+7);render();break;case 'today':week=monday(new Date());render();break;case 'import':$('#ics-file').click();break;case 'restore':$('#backup-file').click();break;case 'backup':download(JSON.stringify(state,null,2),'CatchStudy-'+localDate(new Date())+'.json');break;case 'print':window.print();break;case 'persist':notify(await navigator.storage?.persist?.()?'Dauerhafter Speicher wurde gewährt.':'Der Browser entscheidet über die Speicherfreigabe. Bitte regelmäßig Backups sichern.');break;case 'clear-calendar':if(confirm('Den importierten Stundenplan wirklich löschen?')){const next=clone();next.calendar=null;await commit(next);calendar=[];render();}break;}}catch(e){notify(e.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;$('#course-list').innerHTML=courseList();}});
document.addEventListener('change',async e=>{try{const el=e.target;if(['status','type','prereq'].includes(el.id)){if(el.id==='status')status=el.value;if(el.id==='type')type=el.value;if(el.id==='prereq')prereq=el.value;$('#course-list').innerHTML=courseList();}if(el.id==='target'){target=Math.min(20,Math.max(1,Math.floor(+el.value)||1));render();}if(el.id==='rule'){const next=clone();next.rule=el.value;await commit(next);}if(el.id==='week-date'&&el.value){week=monday(new Date(el.value+'T12:00:00'));render();}}catch(e){notify(e.message);}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),next=clone();try{if(form.id==='course-form')next.progress[form.dataset.id]={status:fd.get('status'),grade:fd.get('grade'),notes:fd.get('notes'),color:fd.has('automatic')?null:fd.get('color')};if(form.id==='elective-form'){const entry={id:form.dataset.id||crypto.randomUUID(),title:fd.get('title').trim(),ects:+fd.get('ects'),grade:fd.get('grade'),completed:fd.has('completed')};if(!entry.title)throw Error('Bitte einen Titel eingeben.');next.electives=next.electives.filter(e=>e.id!==entry.id);next.electives.push(entry);}if(form.id==='event-form'){const ev=visibleEvents[+form.dataset.index];if(fd.get('course'))next.links[ev.key]=fd.get('course');else delete next.links[ev.key];if(fd.has('automatic'))delete next.eventColors[ev.key];else next.eventColors[ev.key]=fd.get('color');}await commit(validateState(next));dialog.close();notify('Gespeichert.');}catch(error){notify(error.message);}});
$('#ics-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('Bitte eine ICS-Datei unter 10 MB wählen.');const text=await file.text(),parsed=parseCalendar(text);const next=clone();next.calendar={text,name:file.name};await commit(next);calendar=parsed;location.hash='schedule';render();notify('Stundenplan importiert und gespeichert.');}catch(error){notify('Import fehlgeschlagen: '+error.message);}finally{e.target.value='';}});
$('#backup-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('Backup ist zu groß.');const next=validateState(JSON.parse(await file.text())),parsed=next.calendar?parseCalendar(next.calendar.text):[];if(!confirm('Aktuelle Daten durch dieses Backup ersetzen?'))return;await commit(next);calendar=parsed;render();notify('Backup wiederhergestellt.');}catch(error){notify('Wiederherstellung fehlgeschlagen: '+error.message);}finally{e.target.value='';}});
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
try{const saved=await load();if(saved)state=validateState(saved);}catch(error){storageReady=false;notify('Gespeicherte Daten konnten nicht geladen werden. Sie werden nicht überschrieben. '+error.message);}
try{if(state.calendar)calendar=parseCalendar(state.calendar.text);}catch(error){notify('Kalender konnte nicht gelesen werden. Dein gespeicherter Import bleibt im Backup erhalten.');}
activateCatalog(state);
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
